




bedtools_coverage:
    bam_dir:  /SAN/vyplab/alb_projects/data/ward_bams/bam_files/

    # Pick out bams from bam_dir with this bam_suffix
    # Also used to strip from file to get sample name
    # e.g. Cont-B_S2.pass2Aligned.sortedByCoord.out.bam becomes Cont-B_S2
    bam_suffix: ".pass2Aligned.sortedByCoord.out.bam"

    bed_path: /SAN/vyplab/sbs_projects/data/nanopore/IPSC_TDP43_KD_direct_rna/intergenic_mean_coverage/simple_gene_downstream_bins_batch_1.bed

    #Make sure trailing slash
    output_dir: /SAN/vyplab/sbs_projects/data/nanopore/IPSC_TDP43_KD_direct_rna/all_downstream_strand_specific_intergenic_coverage/

    #########---------------
    ## BEDTOOLS PARAMETERS
    #########---------------

    # If don't want to use these options, assign them to "" (unless told otherwise)

    # -s - only report hits overlapping on the same strand
    # -S - only report hits overlapping on opposite strands
    strandedness: "-s"

    # Report the depth at each position in each interval
    depth: "-d"

    # what operations to summarise coverage in each intervals from bed_path? All below are valid strings
    # sum, count, count_distinct, min, max, last
    # median, mode, antimode, stdev, sstdev, collapse
    # distinct, concat, freqasc, freqdesc, first, last
    # If just want per-base coverages, assign to an empty list with []
    operations: ["mean"]

    #1-based - which column should operation be performed on? (with depth = -d & a 6 col BED, this is the 8th column)
    operation_column: 8

    # No need to change these unless necessary

    sorted: "-sorted"
    bedtools_path: /SAN/vyplab/alb_projects/tools/bedtools
    samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools
